---
- name: Prometheus Operator CRDs | Download YAML
  include_tasks: "../../../../download/tasks/download_file.yml"
  vars:
    download: "{{ download_defaults | combine(downloads.prometheus_operator_crds) }}"

- name: Prometheus Operator CRDs | Install
  command:
    cmd: "{{ bin_dir }}/kubectl apply -f {{ local_release_dir }}/prometheus-operator-crds.yaml"
  when:
    - "inventory_hostname == groups['kube_control_plane'][0]"
